meta_product_name: "AIS Caritas"
meta_title: "AIS Caritas - Agence Immobilière Sociale"
meta_description: "Agence Immobilière à Vocation Sociale en Ile-de-France"
meta_image: "meta-banner.png" # should exist in `app/assets/images/`
twitter_account: "@virginiaatenza"   # required for Twitter Cards
